#name of the workflow
name: ci-workflow

#Events to trigger on
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#initialize jobs
jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
      # checks the code from repository
      - name: check the code
        uses: actions/checkout@v2
      
      #set up python environment
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      #install packages or dependencies
      - name: install dependencies 
        run: pip install -r requirements.txt
      
      #run python test cases(pytest)
      - name: run test cases
        run: pytest